name: Release

on: 
  release:
    types: [published]

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create build directory
      run: mkdir build
    - name: Create artifact
      uses: montudor/action-zip@v1
      with:
        args: zip -X -r build/pmpro-paytm-gateway-addon.zip . -x *.git* node_modules/\* .* "*/\.*" CODE_OF_CONDUCT.md CONTRIBUTING.md ISSUE_TEMPLATE.md PULL_REQUEST_TEMPLATE.md *.dist composer.* dev-helpers** build**
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pmpro-paytm-gateway-addon.zip
        path: build/pmpro-paytm-gateway-addon.zip
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: build/pmpro-paytm-gateway-addon.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}